### ISSUE TITLE
Enhancement request - TimeLimiter

### ISSUE THREAD

**Issue by patpatpat123** [balajich/resilience4j-helloworld#1]
Hello,

This tutorial along with the Youtube tutorials are very well made.

Many thanks for the work.

If possible, may I ask for a request about the time limiter on this project please? (possibility with Webflux as well?) 

A repo update following the same format, with some explanations on Youtube would be greatly appreciated.

No problem if not, just taking the opportunity to say this is great.

**Comment by balajich** [comment]
Thank you  @patpatpat123  for sharing appreciations. 

I will certainly make my  next video on " I ask for a request about the time limiter on this project please? (possibility with Webflux as well".

Thanks,
Balaji

**Comment by balajich** [comment]
I made a video on your request. I will add webflux example aswell

**Comment by patpatpat123** [comment]
Many thanks for the video.
Very well made like the others.

Just asking:
In the video and in the README, you wrote:
Note: Bulkhead module is added because TimeLimiter needs separate execution thread instead of request thread


And I can confirm, if I comment out this line:
    @Bulkhead(name = "greetingBulkhead", fallbackMethod = "greetingFallBack", type = Bulkhead.Type.THREADPOOL)


The time limiter stops working.
Do you know why please?

**Comment by balajich** [comment]
Please see the comment from developer.

Because a Timelimiter can only interrupt the execution and return an exception, **if it is not running in the same thread.**
Resilience4j is no running your method in another thread implicitly. You have to decide it explicitly by either using a Threadpool Bulkhead, your own ExecutorService or Reactor.

https://github.com/resilience4j/resilience4j/issues/430

Thats the reason you need have a seperate thread
